### ISSUE TITLE
Retrieve .uk domains via Nominet API

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#102]
Nominet have an API for domain queries which we can access as members, can we automate retrieval for indexing?

https://registrars.nominet.uk/uk-namespace/registration-and-domain-management/registration-systems/list-api/rest-api/

**Comment by JimKillock** [comment]
Yes I would say so

**Comment by dantheta** [comment]
It looks like this API is only available to registrars, rather than members.  Although we can generate an API key in our control panel, this (I think) authenticates requests to a different set of APIs.  The token are that is mentioned in the list-api docs isn't available for us.  

We can still get the zone data and perform an equivalent diff, so I've re-opened #97 .
