### ISSUE TITLE
Change "Rejected" flag

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#112]
I'm not sure how the ["rejected" status here was added](https://www.blocked.org.uk/control/ispreports/Vodafone/2481/http://www.wearelava.com): but it seems wrong, as the reply did not receive a rejection. So we need a means to edit / change the "Close report" status.

Maybe we also need a flag of "No decision sent", applicable after 30 days?

**Comment by dantheta** [comment]
I think it was done because there was no ISP reply and we'd wanted to refer it to the BBFC (https://www.blocked.org.uk/control/ispreports/BBFC/http://www.wearelava.com).  Perhaps we need another "close report" status for "no response", allowing the BBFC escalation to be triggered.

I can add  a _reset_ button for the close report status, but there isn't currently an audit trail for status changes outside the normal workflow.  It could make piecing the history together later a bit harder.

**Comment by dantheta** [comment]
Admins can use the status reset button to unresolve an ISP report (sending it back to the 'sent' status)

**Comment by JimKillock** [comment]
Hi Dan; thank you. Can we change the status **names** to:

* Unblock agreed
* Unblock rejected; and add
* No reply 

And as discussed, allow escalation to BBFC in case of no reply. (you can place a time bar on that if you like but we can just be sensible.)

**Comment by dantheta** [comment]
The reset function described at the top has been added, so closing this one in favour of #111 for the status name change & no reply status (they've converged a bit).
