### ISSUE TITLE
Improvements to handling of cancelled reports on admin side

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#137]
While reviewing the ISP reports of new volunteers, I noticed quite a few lacked the option to close a report. 

Some examples:
https://www.blocked.org.uk/control/ispreports/BT-Strict/http://www.coolmathgames.com?tab=categories

https://www.blocked.org.uk/control/ispreports/BT-Strict/http://dramacool.so

https://www.blocked.org.uk/control/ispreports/OpenDNS/http://www.rfnm.org?tab=block

**Comment by dantheta** [comment]
These reports don't have a close with no response option because they've never been sent.  The reports are in pending state waiting for the user to validate their email.

It isn't clear why they haven't been automatically cancelled though.

**Comment by dantheta** [comment]
Ah - they were automatically cancelled.  The pending state applies to the user's verification status.  The user didn't verify their email, so after a while the reports were automatically cancelled, which is considered a "closed" report state.  These reports weren't sent to the ISPs.

**Comment by JimKillock** [comment]
Hi @dantheta and @Mike-ORG — I think this issue is related to #128 also. Unsent reports are a bit confusing from an administration POV.

1. Cancelled reports cannot (always? sometimes?) be submitted again, from the public side, where the user did not verify themselves. Resubmission from the public side (see #128) should be possible, after for instance 30 days.
2. The reports remain in the system on the admin side also; the reports can be resent from there, but it is unclear to me what happens to the original report. Are both kept, or is the original archived? Should the new report be treated differently, or does all correspondence and information belong to the one single item based on the URL? How is all this made clear to the administrator?

**Comment by dantheta** [comment]
> The reports remain in the system on the admin side also; the reports can be resent from there, but it is unclear to me what happens to the original report. Are both kept, or is the original archived? Should the new report be treated differently, or does all correspondence and information belong to the one single item based on the URL? How is all this made clear to the administrator?

Resending a report creates a new report using some of the details from the original; the original is kept, and stays in the cancelled state.  There isn't currently a concrete link between an original report and the resent one, but this will be added in #129.

The original report won't have any correspondence attached, since it wasn't ever sent to the ISPs.  Correspondence is always attached to a specific report - it isn't shared between reports of the same URL, or the same URL/network pair.

Probably the most useful view for the administrator is the "Open" view - reports with cancelled and completed (accepted/rejected/no-decision) statuses are excluded from this.  Combined with url status == blocked, that gives a pretty good view to use as a backlog.

I think the best backlog view for closing reports would probably be:
* Open (status == sent)
* Has replies

The admin could then check the replies and mark them accepted/rejected/no decision to reduce the backlog.

I think the best backlog view for reviews would probably be:
* Open/complete (status in sent,accepted,rejected,no-decision)
* Has replies
* Has not been reviewed

**Comment by dantheta** [comment]
> Cancelled reports cannot (always? sometimes?) be submitted again, from the public side, where the user did not verify themselves. Resubmission from the public side (see #128) should be possible, after for instance 30 days.

This is covered in #79 too.

**Comment by dantheta** [comment]
> NB: I just resent some cancelled reports, but I couldn't then see these listed as 'sent' in the admin system.

The resend function will create new reports for each of the networks that are still blocking the URL and do not have an open report against the url/network pair.

For some of the reports that were resent this afternoon (including the water fountain one), there were no remaining networks blocking the URL so no new reports were created.  The original report will update in the future to an unblocked status - the URL status against an ISP report is a cached value, updated on a schedule.

**Comment by dantheta** [comment]
At some point I should write up the report statuses on the blocked or github wiki, but for reference the currently supported values are:

Open:
* new
* pending
* sent

Closed:
* abuse
* cancelled
* auto-closed

Completed/reviewed:
* rejected
* accepted (fka unblocked)
* no-decision

Completed/reopened:
* resent
* escalated

The headings correspond roughly to the filter views available in the ISP reports control panel.

Do we want to separate out the backlog views for the different kinds of review activity?  We've got:

* qualitative grading of ISP responses (matches/does not match policy, as well as categorizing)
* Identifying completed reports, where the ISP has accepted/rejected the reports and marking the reports "completed"

Are these treated as the same review activity?

**Comment by Mike-ORG** [comment]
How about I tell our volunteers to focus, for now, on open reports that have replies only?

**Comment by JimKillock** [comment]
It may be that we can solve the problem for now by making these values transparent on the review screen:

Closed:

- abuse
- cancelled
- auto-closed

Completed/reopened:

- resent
- escalated

If these values appear where the "Close Report" button would normally be, but are not editable, then the reviewer will have a better idea of what they need to do with it (eg, check the green ticks are in place, and move on).

**Comment by dantheta** [comment]
The status is now shown in the status area in the top right.

**Comment by Mike-ORG** [comment]
@JimKillock I'm not suggesting ignoring reports without replies permanently, but I am searching for the best way to direct the volunteers so they can make progress. This situation is getting very confusing and I want to keep it as simple as possible for the volunteers. Avoiding no-replies seems like the lowest hanging fruit at the moment.

If the following is true:

Open:

    new
    pending
    sent

Closed:

    abuse
    cancelled
    auto-closed

- then how can the following reports be both listed as both pending AND cancelled? Does that mean they are open or closed?

https://www.blocked.org.uk/control/ispreports/BT-Strict/http://www.coolmathgames.com?tab=categories

https://www.blocked.org.uk/control/ispreports/BT-Strict/http://dramacool.so

https://www.blocked.org.uk/control/ispreports/OpenDNS/http://www.rfnm.org?tab=block

**Comment by dantheta** [comment]
On those reports, the user verification is pending, (the left block is all about the user) and the report itself is cancelled.  I can make that clearer, definitely.

**Comment by JimKillock** [comment]
@Mike-ORG I understand, however the goal is to have publishable, so complete, information. So we're better off improving the navigation rather than omitting analysis of part of the data. For now you can just say to users that sometimes reports can't be closed, and we will make it clearer why that is in future.

**Comment by JimKillock** [comment]
I think what @dantheta has implemented makes the situation fairly clear now, what do you think @Mike-ORG? 

The “cancelled” status is shown on the page; thus the reviewers can be told that they should review each site, but do not need to “close” the report.

My only worry now is making sure that “cancelled” reports are also “reviewed” 
- Do we need to check this by visually looking at each report for the green ticks? 
- Or is there a simpler way to check for cancelled (but valid) complaints, so we can send these on?

**Comment by Mike-ORG** [comment]
@JimKillock As you suggest, I will let volunteers know that sometimes reports can't be closed so they can just do the other tabs in those cases. That's easy enough, thanks.
