### ISSUE TITLE
Add page for BBFC complaints

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#92]
Have a page for sites referred to BBFC showing:

- Sitename
- Original complaint text
- Date referred to BBFC
- Rsponse from BBFC (text)
- Response from BBFC (block / unblock)
- Show all mobile statuses (blocked / unblocked etc) for the site

**Comment by dantheta** [comment]
New page is at: https://www.blocked.org.uk/bbfc-reports

I've overhauled the ISP reports page a bit too.

The banner/explanatory page text can be edited in the CMS.

**Comment by JimKillock** [comment]
That's great Dan! Do you know why barlowvineyards.com is not showing an 'unblocked' or other status?

**Comment by dantheta** [comment]
There isn't a BBFC reply for barlowvineyards.com.  Since the BBFC reports aren't connected to any probes there isn't any automatic detection of unblocked/refused; an administrator can select a reply to close the report with an unblocked or declined status, and this gets displayed on the /bbfc-reports page.

**Comment by JimKillock** [comment]
Thanks dan, closing this. Looks like Barlow Vineyards should not have been sent, as there was no block on any mobile ISP. Wil keep an eye on this, in case that is possible to do (AIUI it shouldn't (now?) be possible).
